import { invoke } from '@tauri-apps/api/core';
import { MediaItem, MediaSource, PlayUrl, SourceConfig } from '../types';

// v2.3.0 统一 JS 引擎源适配器（律云版）
// 执行 spider 脚本驱动任意音乐源（洛雪风格 / 网上各种 JS 音乐蜘蛛）。脚本经 Rust
// run_spider 命令在 QuickJS 沙箱内运行，网络请求由 fetch 桥接回 Rust 代理。
// spider 约定函数：search(key) / detail(id) / play(url)
// 返回遵循常见音乐蜘蛛格式：{ list:[{ id, name, artist, album, pic }] }

// v2.4.4 #1：CommonJS 垫片改为「按需 + 幂等」，修「同一份源第二次添加就搜不到」。
//
// 原实现在 v2.4.3 引入，无条件前置垫片且不做任何判重：
//     return COMMONJS_SHIM + code.replace(STRIP_ESM, '');
// 一旦 spider 字段里已经含过垫片（保存/导入流程写回过一次），再 catsvodize 就会变成
//     var module={exports:{}};var exports=module.exports;
//     var module={exports:{}};var exports=module.exports;   ← 重复声明
// 在 rquickjs 0.6 / Android 的 QuickJS 上 eval 直接抛
//     Exception generated by QuickJS
// （调试面板实测：L1 就是垫片那一行），表现为「首次添加搜不到、删掉重新粘贴同一份字符串就好了」。
//
// 三条修法：
//   1) 按需：只有脚本真的用到 CommonJS（module.exports / exports.xxx / require(）才加垫片。
//      纯 `var spider = {...}` 形态的源本就不需要它，不该被塞。
//   2) 幂等：已经含垫片的字符串不再重复前置（双保险，覆盖「按需」漏判的情况）。
//   3) 收紧 STRIP_ESM：去掉 `\s*`，只剥顶格的 export/import 声明，
//      避免把缩进在函数体里的同名行、或模板字符串里的内容一起删掉。
const STRIP_ESM = /^(?:export|import)\s+.*$/gm;
const COMMONJS_SHIM = 'var module={exports:{}};var exports=module.exports;\n';
/** 脚本是否真的依赖 CommonJS 运行时（决定要不要垫片） */
const NEEDS_COMMONJS = /\bmodule\s*\.\s*exports\b|\bexports\s*\.|\brequire\s*\(/;
/** 垫片是否已经存在（幂等判据） */
const HAS_SHIM = /var\s+module\s*=\s*\{\s*exports\s*:\s*\{\s*\}\s*\}/;

function catsvodize(code: string): string {
  const stripped = code.replace(STRIP_ESM, '');
  // 已含垫片 → 原样返回，绝不重复前置
  if (HAS_SHIM.test(stripped)) return stripped;
  // 不依赖 CommonJS → 不加垫片（纯 spider 对象脚本走这条）
  if (!NEEDS_COMMONJS.test(stripped)) return stripped;
  return COMMONJS_SHIM + stripped;
}

export const __test_catsvodize = catsvodize;

// CatVod/音乐源命名兼容：优先试 Content 长名，调用失败或未声明则回退短名。
// 纯全局函数音乐源两条都命中同一函数也无副作用（二次调用只是多走一次失败分支）。
const COMPAT: Record<string, [string, string]> = {
  search: ['searchContent', 'search'],
  detail: ['detailContent', 'detail'],
  play: ['playerContent', 'play'],
};

export function createJsSource(cfg: SourceConfig): MediaSource {
  const jsCfg = cfg as any;
  let cachedCode: string | null = null;
  // v2.4.1 #I：缓存要跟「脚本来源」绑定。
  // 当前所有调用点（aggregateSearch / test / resolvePlay）都是每次新建适配器实例，
  // 正常用不到这层校验；但一旦将来有人为了性能复用实例，旧实现会一直返回换源前的脚本，
  // 表现为「换了源却还在用老脚本」。加指纹是低成本的长期防御。
  let cachedKey: string | null = null;

  /** 脚本来源指纹：spider 内联内容 + 两个远程地址，任一变化即视为换源 */
  function codeKey(): string {
    return [jsCfg.spider ?? '', jsCfg.spiderUrl ?? '', jsCfg.api ?? '', jsCfg.code ?? ''].join('\u0000');
  }

  async function loadCode(): Promise<string> {
    // 来源变了 → 丢弃旧缓存重新加载
    if (cachedCode && cachedKey === codeKey()) return cachedCode;
    if (cachedCode) {
      cachedCode = null;
      cachedKey = null;
    }
    let raw: string;
    if (jsCfg.spider) {
      raw = jsCfg.spider as string;
    } else if (jsCfg.spiderUrl) {
      raw = await invoke<string>('fetchsource', { url: jsCfg.spiderUrl });
    } else if (jsCfg.api) {
      raw = await invoke<string>('fetchsource', { url: jsCfg.api });
    }
    // v2.4.1 #G：兜底识别 `code` 字段。正常导入路径已由 sourceFetch.normalize 归一化为
    // spider，这里再兜一层，覆盖「绕过导入路径直接构造配置」的场景（如手动编辑 localStorage）。
    else if (jsCfg.code) {
      raw = jsCfg.code as string;
    } else {
      throw new Error('JS 源缺少 spider 脚本（需提供 spider / spiderUrl / api / code 之一）');
    }
    // v2.4.3 #A：加载即预处理（剥 ESM 残留 + CommonJS 垫片），缓存「处理后」的代码，
    // 后续每次 call 直接复用，避免重复预处理。
    cachedCode = catsvodize(raw);
    cachedKey = codeKey();
    return cachedCode;
  }

  // 解析 spider 原始返回：JSON 字符串二次解析（CatVod 常返回 JSON 字符串而非对象）。
  function parseSpider(raw: string): any {
    let parsed: any;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return raw;
    }
    if (typeof parsed === 'string') {
      try {
        const again = JSON.parse(parsed);
        if (again && typeof again === 'object') return again;
      } catch {
        /* 本来就是普通字符串结果（如 play 返回的裸 URL），保持原样 */
      }
    }
    return parsed;
  }

  async function call(func: string, args: string[]): Promise<any> {
    const code = await loadCode();
    // v2.4.3 #A：CatVod/音乐源命名兼容。优先长名（searchContent 等），失败或未声明回退短名。
    const [primary, fallback] = COMPAT[func] ?? [func, func];
    const names = primary === fallback ? [primary] : [primary, fallback];
    let lastErr: unknown;
    for (const name of names) {
      try {
        const raw = await invoke<string>('run_spider', {
          // v2.3.11：name 供 Rust 侧标注日志归属（调试面板能看出是哪个源在请求）
          payload: { code, func: name, args, api: jsCfg.api, ext: jsCfg.ext, name: cfg.name },
        });
        return parseSpider(raw);
      } catch (e) {
        lastErr = e; // 长名未定义/调用失败 → 试下一个候选
      }
    }
    const err = lastErr as any;
    throw new Error(err?.message || `调用 spider 失败：${func}`);
  }

  function toItems(list: any[]): MediaItem[] {
    if (!Array.isArray(list)) return [];
    return list.map((v: any) => ({
      id: String(v.id ?? v.vod_id ?? ''),
      sourceId: cfg.id,
      sourceName: cfg.name,
      title: v.name ?? v.title ?? v.vod_name ?? '未命名',
      artist: v.artist ?? v.singer ?? v.vod_actor ?? '',
      album: v.album ?? '',
      cover: v.pic ?? v.cover ?? v.vod_pic ?? '',
      mediaType: 'music' as const,
      // v2.5.0 #6-3：透出付费/试听/原唱字段。spider 可能用不同命名，
      // 这里做容错读取（vip/trial/original 优先，其次各源历史字段）。
      vip: !!(
        v.vip ??
        v.pay ??
        v.payFlag ??
        (typeof v.fee === 'number' && v.fee !== 0 && v.fee !== 8) ??
        false
      ),
      trial: !!(v.trial ?? v.freeTrial ?? (v.fee === 8)),
      original: !!(v.original ?? v.isoriginal ?? false),
      raw: v,
    }));
  }

  return {
    async search(keyword: string) {
      const data = await call('search', [keyword]);
      const list = data?.list ?? (Array.isArray(data) ? data : []);
      return toItems(list);
    },

    async getPlayUrl(itemId: string): Promise<PlayUrl> {
      const data = await call('play', [itemId]);
      const url = typeof data === 'string' ? data : data?.url ?? '';
      return { url };
    },

    /**
     * v2.4.9 #1.3/#1.5.6：detail 通道改造（封面回填的前提）。
     *
     * 旧实现只把裸 id 传给 spider：`call('detail', [itemId])`。而本工程的音乐源
     * （酷我 / 网易云 / 咪咕）在 detail 里要靠**歌名 + 歌手**去兜底封面——酷我是
     * `kgCover(name, artist)` 回落到酷狗 union_cover，网易云是匿名 picUrl 常空需回查。
     * 只给 id 时 name/artist 全空，兜底必然返回空串：封面永远补不上，
     * 这就是「1.3 酷我无封面」的真根因之一（另一半是过去 getDetail 零调用点）。
     *
     * 现在与 getLyric 保持同一契约：把 {id,name,title,artist,album} 序列化为 JSON
     * 字符串作为第 1 个参数，同时把裸 id 作为第 2 个参数带上，兼容只吃 id 的老源。
     * （Rust 侧 args 是字符串数组，会原样展开成 func(...args)，传不了对象。）
     */
    async getDetail(itemOrId: MediaItem | string) {
      const obj: any = typeof itemOrId === 'string' ? { id: itemOrId } : itemOrId;
      const id = String(obj?.id ?? '');
      const payload = {
        id,
        name: obj?.title ?? obj?.name ?? '',
        title: obj?.title ?? obj?.name ?? '',
        artist: obj?.artist ?? obj?.singer ?? '',
        album: obj?.album ?? '',
        pic: obj?.cover ?? '',
      };
      try {
        const data = await call('detail', [JSON.stringify(payload), id]);
        // 形态兼容：spider 的 detail 有两种常见返回约定
        //   1) { list:[{...}] }  —— CatVod 风格
        //   2) { id,name,artist,pic }  —— 单对象（本工程 4 个直连源都是这种）
        // 旧实现只认 1)，遇到酷我那种单对象会走到「拿不到内容」分支抛错，
        // 封面回填被静默吞掉 —— 表现为「改了 getDetail 调用点，封面还是没有」。
        let first: any;
        if (Array.isArray(data)) first = data[0];
        else if (Array.isArray(data?.list)) first = data.list[0];
        else if (data && typeof data === 'object') first = data;
        const items = first ? toItems([first]) : [];
        if (items[0]) return items[0];
        // v2.4.1 #I：详情拿不到内容时明确抛错，不再静默返回空 title 占位对象。
        // 此前返回 { title: '' } 会让上层拿到一个「没有歌名的歌」，
        // 换源后播放旧结果时表现为「歌名莫名消失」，极难定位。
        throw new Error('该歌曲在当前源中已不可用（可能已换源或下架）');
      } catch (e: any) {
        // 只透传我们自己抛的语义化错误；其余（网络/解析失败）也统一升级为可见错误
        throw new Error(e?.message || '获取歌曲详情失败');
      }
    },

    /**
     * v2.4.8 #1：歌词通道。
     * spider 的 lyric(i) 有多套常见返回约定，这里统一归一化：
     *   1) { lyric: '<base64>' }      —— 酷狗系（krcs/lyrics.kugou 返回 base64 LRC）
     *   2) { lyric: '<lrc 原文>' }    —— 直接给 LRC 文本
     *   3) { lyric: ['行1','行2'] }   —— 纯文本行数组（无时间轴）
     *   4) 裸字符串 base64 / LRC
     * 参数同时带上 id 与 title/name，兼容不同 spider 的取值习惯。
     */
    async getLyric(item: MediaItem | string) {
      // 兼容两种调用：传 MediaItem（推荐，含 id/title）或只传 id 字符串
      const obj: any = typeof item === 'string' ? { id: item } : item;
      const id = String(obj?.id ?? '');
      // 注意：Rust 侧 args 是「字符串数组」，会原样展开成 func(...args) —— 传不了对象。
      // 因此这里把 {id,title,name} 序列化成 JSON 字符串传入，源侧用 JSON.parse 解开。
      // 为兼容老式只接受裸 id 的源，同时也把 id 作为第 2 个参数传入。
      const payload = { id, title: obj?.title ?? obj?.name ?? '', name: obj?.name ?? obj?.title ?? '' };
      const data = await call('lyric', [JSON.stringify(payload), id]);
      // 解包：{ lyric: x } / { lrc: x } / 裸值
      let raw = data?.lyric ?? data?.lrc ?? data;
      if (typeof raw !== 'string' && !Array.isArray(raw)) {
        if (raw == null) return '';
        raw = String(raw);
      }
      if (Array.isArray(raw)) return raw.map((t: any) => String(t));
      const s = raw as string;
      if (!s) return '';
      // 判断是否 base64：酷狗歌词接口返回的是 base64 编码的 LRC。
      // 用「是否含 LRC 时间轴标记」做判据 —— 已经是明文 LRC 就不动它。
      if (!/\[\d{1,2}:\d{1,2}/.test(s) && looksLikeBase64(s)) {
        try {
          const decoded = atob(s);
          // atob 结果按 UTF-8 还原（base64 里常是中文）
          return utf8Decode(decoded);
        } catch {
          return s;
        }
      }
      return s;
    },

    /**
     * v2.4.9 #2.2：歌手全曲（作者页数据源）。
     * spider 的 artist(i) 入参是 JSON 串（un() 解开），取 artist / singername / name
     * 任一字段定位歌手；返回 { list:[...] }。老式源没有 artist 函数时 call 会抛，
     * 由聚合层静默跳过并回退到按歌手名搜索。
     */
    async getArtistSongs(artistName: string) {
      const name = String(artistName ?? '').trim();
      if (!name) return [];
      const payload = { artist: name, singername: name, name, title: name };
      const data = await call('artist', [JSON.stringify(payload), name]);
      let list: any[];
      if (Array.isArray(data)) list = data;
      else if (Array.isArray(data?.list)) list = data.list;
      else if (data && typeof data === 'object') list = [data];
      else list = [];
      const items = toItems(list);
      // 作者页要的是「这个歌手的歌」。源返回的是该歌手作品库，正常情况是干净的，
      // 但翻唱/合辑可能混入他人曲目，这里做一次宽松筛选：
      // 歌手名相互包含即视为命中（「许嵩&Kent」与「许嵩」互含，合唱曲不会被误杀）。
      const hit = (a: string) =>
        !a || a === name || a.includes(name) || name.includes(a);
      return items.filter((it) => hit(String(it.artist ?? '')));
    },

    async test() {
      try {
        await loadCode();
        return true;
      } catch {
        return false;
      }
    },
  };
}

/** v2.4.8 #1：base64 粗略判据（去空白后全为 base64 字符且长度合理） */
function looksLikeBase64(s: string): boolean {
  const t = s.replace(/\s+/g, '');
  if (t.length < 24) return false;
  return /^[A-Za-z0-9+/]+={0,2}$/.test(t);
}

/** v2.4.8 #1：atob 得到的「二进制字符串」按 UTF-8 还原成正常文本 */
function utf8Decode(bin: string): string {
  try {
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i) & 0xff;
    return new TextDecoder('utf-8').decode(bytes);
  } catch {
    return bin;
  }
}
