import { invoke } from '@tauri-apps/api/core';
import { MediaItem, MediaSource, PlayUrl, SourceConfig } from '../types';

// v2.3.0 统一 JS 引擎源适配器（律云版）
// 执行 spider 脚本驱动任意音乐源（洛雪风格 / 网上各种 JS 音乐蜘蛛）。脚本经 Rust
// run_spider 命令在 QuickJS 沙箱内运行，网络请求由 fetch 桥接回 Rust 代理。
// spider 约定函数：search(key) / detail(id) / play(url)
// 返回遵循常见音乐蜘蛛格式：{ list:[{ id, name, artist, album, pic }] }

// v2.4.4 #1：CommonJS 垫片改为「按需 + 幂等」，修「同一份源第二次添加就搜不到」。
//
// 原实现在 v2.4.3 引入，无条件前置垫片且不做任何判重：
//     return COMMONJS_SHIM + code.replace(STRIP_ESM, '');
// 一旦 spider 字段里已经含过垫片（保存/导入流程写回过一次），再 catsvodize 就会变成
//     var module={exports:{}};var exports=module.exports;
//     var module={exports:{}};var exports=module.exports;   ← 重复声明
// 在 rquickjs 0.6 / Android 的 QuickJS 上 eval 直接抛
//     Exception generated by QuickJS
// （调试面板实测：L1 就是垫片那一行），表现为「首次添加搜不到、删掉重新粘贴同一份字符串就好了」。
//
// 三条修法：
//   1) 按需：只有脚本真的用到 CommonJS（module.exports / exports.xxx / require(）才加垫片。
//      纯 `var spider = {...}` 形态的源本就不需要它，不该被塞。
//   2) 幂等：已经含垫片的字符串不再重复前置（双保险，覆盖「按需」漏判的情况）。
//   3) 收紧 STRIP_ESM：去掉 `\s*`，只剥顶格的 export/import 声明，
//      避免把缩进在函数体里的同名行、或模板字符串里的内容一起删掉。
const STRIP_ESM = /^(?:export|import)\s+.*$/gm;
const COMMONJS_SHIM = 'var module={exports:{}};var exports=module.exports;\n';
/** 脚本是否真的依赖 CommonJS 运行时（决定要不要垫片） */
const NEEDS_COMMONJS = /\bmodule\s*\.\s*exports\b|\bexports\s*\.|\brequire\s*\(/;
/** 垫片是否已经存在（幂等判据） */
const HAS_SHIM = /var\s+module\s*=\s*\{\s*exports\s*:\s*\{\s*\}\s*\}/;

function catsvodize(code: string): string {
  const stripped = code.replace(STRIP_ESM, '');
  // 已含垫片 → 原样返回，绝不重复前置
  if (HAS_SHIM.test(stripped)) return stripped;
  // 不依赖 CommonJS → 不加垫片（纯 spider 对象脚本走这条）
  if (!NEEDS_COMMONJS.test(stripped)) return stripped;
  return COMMONJS_SHIM + stripped;
}

export const __test_catsvodize = catsvodize;

// CatVod/音乐源命名兼容：优先试 Content 长名，调用失败或未声明则回退短名。
// 纯全局函数音乐源两条都命中同一函数也无副作用（二次调用只是多走一次失败分支）。
const COMPAT: Record<string, [string, string]> = {
  search: ['searchContent', 'search'],
  detail: ['detailContent', 'detail'],
  play: ['playerContent', 'play'],
};

export function createJsSource(cfg: SourceConfig): MediaSource {
  const jsCfg = cfg as any;
  let cachedCode: string | null = null;
  // v2.4.1 #I：缓存要跟「脚本来源」绑定。
  // 当前所有调用点（aggregateSearch / test / resolvePlay）都是每次新建适配器实例，
  // 正常用不到这层校验；但一旦将来有人为了性能复用实例，旧实现会一直返回换源前的脚本，
  // 表现为「换了源却还在用老脚本」。加指纹是低成本的长期防御。
  let cachedKey: string | null = null;

  /** 脚本来源指纹：spider 内联内容 + 两个远程地址，任一变化即视为换源 */
  function codeKey(): string {
    return [jsCfg.spider ?? '', jsCfg.spiderUrl ?? '', jsCfg.api ?? '', jsCfg.code ?? ''].join('\u0000');
  }

  async function loadCode(): Promise<string> {
    // 来源变了 → 丢弃旧缓存重新加载
    if (cachedCode && cachedKey === codeKey()) return cachedCode;
    if (cachedCode) {
      cachedCode = null;
      cachedKey = null;
    }
    let raw: string;
    if (jsCfg.spider) {
      raw = jsCfg.spider as string;
    } else if (jsCfg.spiderUrl) {
      raw = await invoke<string>('fetchsource', { url: jsCfg.spiderUrl });
    } else if (jsCfg.api) {
      raw = await invoke<string>('fetchsource', { url: jsCfg.api });
    }
    // v2.4.1 #G：兜底识别 `code` 字段。正常导入路径已由 sourceFetch.normalize 归一化为
    // spider，这里再兜一层，覆盖「绕过导入路径直接构造配置」的场景（如手动编辑 localStorage）。
    else if (jsCfg.code) {
      raw = jsCfg.code as string;
    } else {
      throw new Error('JS 源缺少 spider 脚本（需提供 spider / spiderUrl / api / code 之一）');
    }
    // v2.4.3 #A：加载即预处理（剥 ESM 残留 + CommonJS 垫片），缓存「处理后」的代码，
    // 后续每次 call 直接复用，避免重复预处理。
    cachedCode = catsvodize(raw);
    cachedKey = codeKey();
    return cachedCode;
  }

  // 解析 spider 原始返回：JSON 字符串二次解析（CatVod 常返回 JSON 字符串而非对象）。
  function parseSpider(raw: string): any {
    let parsed: any;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return raw;
    }
    if (typeof parsed === 'string') {
      try {
        const again = JSON.parse(parsed);
        if (again && typeof again === 'object') return again;
      } catch {
        /* 本来就是普通字符串结果（如 play 返回的裸 URL），保持原样 */
      }
    }
    return parsed;
  }

  async function call(func: string, args: string[]): Promise<any> {
    const code = await loadCode();
    // v2.4.3 #A：CatVod/音乐源命名兼容。优先长名（searchContent 等），失败或未声明回退短名。
    const [primary, fallback] = COMPAT[func] ?? [func, func];
    const names = primary === fallback ? [primary] : [primary, fallback];
    let lastErr: unknown;
    for (const name of names) {
      try {
        const raw = await invoke<string>('run_spider', {
          // v2.3.11：name 供 Rust 侧标注日志归属（调试面板能看出是哪个源在请求）
          payload: { code, func: name, args, api: jsCfg.api, ext: jsCfg.ext, name: cfg.name },
        });
        return parseSpider(raw);
      } catch (e) {
        lastErr = e; // 长名未定义/调用失败 → 试下一个候选
      }
    }
    const err = lastErr as any;
    throw new Error(err?.message || `调用 spider 失败：${func}`);
  }

  function toItems(list: any[]): MediaItem[] {
    if (!Array.isArray(list)) return [];
    return list.map((v: any) => ({
      id: String(v.id ?? v.vod_id ?? ''),
      sourceId: cfg.id,
      sourceName: cfg.name,
      title: v.name ?? v.title ?? v.vod_name ?? '未命名',
      artist: v.artist ?? v.singer ?? v.vod_actor ?? '',
      album: v.album ?? '',
      cover: v.pic ?? v.cover ?? v.vod_pic ?? '',
      mediaType: 'music' as const,
      raw: v,
    }));
  }

  return {
    async search(keyword: string) {
      const data = await call('search', [keyword]);
      const list = data?.list ?? (Array.isArray(data) ? data : []);
      return toItems(list);
    },

    async getPlayUrl(itemId: string): Promise<PlayUrl> {
      const data = await call('play', [itemId]);
      const url = typeof data === 'string' ? data : data?.url ?? '';
      return { url };
    },

    async getDetail(itemId: string) {
      try {
        const data = await call('detail', [itemId]);
        const list = data?.list ?? (Array.isArray(data) ? data : []);
        const items = toItems(list);
        if (items[0]) return items[0];
        // v2.4.1 #I：详情拿不到内容时明确抛错，不再静默返回空 title 占位对象。
        // 此前返回 { title: '' } 会让上层拿到一个「没有歌名的歌」，
        // 换源后播放旧结果时表现为「歌名莫名消失」，极难定位。
        throw new Error('该歌曲在当前源中已不可用（可能已换源或下架）');
      } catch (e: any) {
        // 只透传我们自己抛的语义化错误；其余（网络/解析失败）也统一升级为可见错误
        throw new Error(e?.message || '获取歌曲详情失败');
      }
    },

    async test() {
      try {
        await loadCode();
        return true;
      } catch {
        return false;
      }
    },
  };
}
